### ISSUE TITLE
Подсвечивать цветами время исполнения инструкций

### ISSUE THREAD

**Issue by Vadimatorik** [Asubuhi824lia/AVR-counting#2]
1 - зеленый
2 - желтый
3+ - красный
Если есть 2/4 - то каждый независимое число.

**Comment by Asubuhi824lia** [comment]
![image](https://user-images.githubusercontent.com/31811748/215433402-1c176da9-f420-477d-b99a-48399943d50e.png)

Дополнительно увеличила ширину столбцов, т.к. 3-циферное значение не помещалось в 1 строку.
