### ISSUE TITLE
Добавить возможность по галочке скрывать поля

### ISSUE THREAD

**Issue by Vadimatorik** [Asubuhi824lia/AVR-counting#5]
Представляю себе это так.
![image](https://user-images.githubusercontent.com/14297516/214523963-38243f84-d0b8-407f-9fef-df88bb970145.png)

**Comment by Asubuhi824lia** [comment]
[Запись экрана от 30.01.2023 17:57:27.webm](https://user-images.githubusercontent.com/31811748/215458986-612dd249-cda9-47b7-96a5-7b41d065f1e8.webm)
